### ISSUE TITLE
Button missing in Calibre 5.16

### ISSUE THREAD

**Issue by morganmay** [goodlibs/calibre-opds-client#14]
**Describe the bug**
The OPDS Client button doesn't appear in the Toolbars & menus dialog box after installing the plugin in Calibre 5.16 on Arch Linux.

**To reproduce**
1. Install Calibre 5.16 binary, as per <https://calibre-ebook.com/download_linux>.
2. Follow steps 2-4.iii of <https://github.com/goodlibs/calibre-opds-client#hammer_and_wrench-installation>

**Expected behavior**
There should be an OPDS Client button under Available actions, but there isn't.

**Logs or screenshots**
`calibre-customize -b .` yields:
```
Plugin updated: OPDS Client (1, 0, 0)
```

Running `calibre` from the commandline yields this error:
```
Traceback (most recent call last):
  File "calibre/gui2/ui.py", line 135, in __init__
  File "calibre/gui2/ui.py", line 153, in init_iaction                        
  File "calibre/customize/__init__.py", line 626, in load_actual_plugin
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.opds_client.ui", line 10, in <module>
    from calibre_plugins.opds_client.main import OpdsDialog
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.opds_client.main", line 32, in <module>
    from calibre_plugins.opds_client.model import OpdsBooksModel
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.opds_client.model", line 11, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```

**System information**
- Plugin version: 1.0.0
- Calibre version: 5.16
- Operating system: Arch Linux

**Comment by fuji44** [comment]
I am experiencing the same phenomenon.

- Plugin version: 1.0.0
- Calibre version: 5.17
- Operating system: Windows 10 20H2 (19042.928)

**Comment by fuji44** [comment]
I've tried manipulating it to the point where it displays the toolbar & menu settings screen in debug mode. It still doesn't seem to output any useful information.

```
calibre デバッグログ
calibre 5.17 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: ja
Successfully initialized third party plugins: OPDS Client (1, 0, 0)
calibre 5.17 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: ja
Successfully initialized third party plugins: OPDS Client (1, 0, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.96531791907513 x 94.07407407407408
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.73] splash screen shown
[0.73] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
[1.48] main UI initialized...
[1.48] Hiding splash screen
Starting QuickView
```

**Comment by fuji44** [comment]
When I closed the application, the following log was appended.

```
Traceback (most recent call last):
  File "calibre\gui2\ui.py", line 135, in __init__
  File "calibre\gui2\ui.py", line 153, in init_iaction
  File "calibre\customize\__init__.py", line 626, in load_actual_plugin
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.opds_client.ui", line 10, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.opds_client.main", line 32, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.opds_client.model", line 11, in <module>
ModuleNotFoundError: No module named 'urllib2'
[44.03] splash screen hidden
[44.03] Started up in 44.03 seconds with 15 books
```

**Comment by fuji44** [comment]
I was able to display the OPDS button by modifying the `urllib2` and `urlparse` imports.
However, there seems to be a lot of problems to use it in my environment, such as `feed.headers["server"]` cannot be read, and the format of `strptime` does not match.

**Comment by chernistry** [comment]
Same here in 5.44

**Comment by lawipac** [comment]
Frist install of this plugin under Calibre 6.5  cannot find the so call button 
"Select OPDS Client under Available actions on the left side." 
I'm guessing the issue is the same. it looks like this plugin has not bee updated for a long long time.

**Comment by bulletproof2k** [comment]
Calibre 6.17.0 
The plugin is installed normally, but there is no button.
